version: '3'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-s3
    network_mode: "host"  # Use host network so container ports are exposed directly on host IP
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_DOMAIN: s3bkids.bebakids.com
      MINIO_SERVER_URL: https://s3bkids.bebakids.com
      MINIO_NOTIFY_WEBHOOK_ENABLE: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT: "http://localhost:3000/webhook"
    volumes:
      - /mnt/nas_storage:/data
    command: server --address ":9000" --console-address ":9001" /data
    restart: always
    
  image-resizer:
    build:
      context: ./image-resizer
      dockerfile: Dockerfile
    container_name: image-resizer
    network_mode: "host"  # Use host network like MinIO
    environment:
      - MINIO_ENDPOINT=localhost
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_USER}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD}
      - BUCKET_NAME=products
    volumes:
      - ./image-resizer/temp:/usr/src/app/temp
    depends_on:
      - minio
    restart: always
    
  ftp-sync:
    build:
      context: ./ftp-sync
      dockerfile: Dockerfile
    container_name: ftp-sync
    network_mode: "host"  # Isti režim mreže kao i ostali servisi
    environment:
      # FTP konfiguracija - učitavanje iz .env fajla
      - FTP_HOST=${FTP_HOST}
      - FTP_PORT=${FTP_PORT}
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
      - FTP_SECURE=${FTP_SECURE}
      - FTP_REMOTE_PATH=${FTP_REMOTE_PATH}
      
      # MinIO konfiguracija - koristi iste varijable kao i ostali servisi
      - MINIO_ENDPOINT=localhost
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_USER}
      - MINIO_SECRET_KEY=${MINIO_PASSWORD}
      - MINIO_BUCKET=products
      
      # Raspored pokretanja
      - CRON_SCHEDULE=${FTP_CRON_SCHEDULE:-0 */1 * * *}
      
      # Dodatne opcije
      - LOOKBACK_HOURS=${FTP_LOOKBACK_HOURS:-24}
      - DELETE_AFTER_UPLOAD=${FTP_DELETE_AFTER_UPLOAD:-false}
    volumes:
      - ./ftp-sync/temp:/app/temp
    depends_on:
      - minio
      - image-resizer
    restart: always
